# Generated by Django 5.0 on 2024-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200526_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='behavior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='defender',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ivents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rescuer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='scout',
            field=models.IntegerField(default=0),
        ),
    ]
