# Generated by Django 5.0 on 2024-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_behavior_profile_defender_profile_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sum_points',
            field=models.IntegerField(default=0),
        ),
    ]
