# Generated by Django 5.0 on 2024-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achivments',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interes',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Интересы'),
        ),
    ]
